/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_BAB837B6__
#define __PLUGINEDITOR_H_BAB837B6__

#include "JuceHeader.h"
#include "PluginProcessor.h"

class Radium_Compressor;

//==============================================================================
/**
*/
class RadiumCompressorAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    RadiumCompressorAudioProcessorEditor (RadiumCompressorAudioProcessor* ownerFilter);
    ~RadiumCompressorAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    //void paint (Graphics& g);

    LookAndFeel_V2 *look_and_feel;
    Radium_Compressor *radium_compressor;

    void update_gui();

    void paint (Graphics& g);
};


#endif  // __PLUGINEDITOR_H_BAB837B6__
